# Generated by Django 3.0.3 on 2020-07-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveydata',
            name='secound',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
