# Generated by Django 3.0.3 on 2020-07-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20200703_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveydata',
            name='fifth',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='surveydata',
            name='fourth',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='surveydata',
            name='third',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
